name: Build and Release uYouEnhanced

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        default: "17.0"
      uyou_version:
        default: "3.0.4"
      decrypted_youtube_url:
        default: ""
      bundle_id:
        default: "com.google.ios.youtube"
      app_name:
        default: "YouTube"
      commit_id:
        default: ""
      upload_artifact:
        default: false
      create_release:
        default: true

jobs:
  build:
    name: Build uYouEnhanced
    runs-on: macos-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.2.1
        with:
          path: main
          ref: ${{ github.event.inputs.commit_id || github.ref }}
          submodules: recursive

      - name: Install Dependencies
        run: |
          brew update
          brew install ldid dpkg make
          ldid --version

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Setup Theos
        uses: actions/checkout@v4.2.1
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          mkdir -p $THEOS/sdks
          wget -q https://github.com/theos/sdks/raw/master/iPhoneOS${{ inputs.sdk_version }}.sdk.tar.xz -O sdk.tar.xz
          tar -xf sdk.tar.xz -C $THEOS/sdks
          rm sdk.tar.xz
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.2.1
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Prepare YouTube iPA
        id: prepare_youtube
        run: |
          wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa || { echo "Failed to download YouTube IPA"; exit 1; }
          cd ${{ github.workspace }}/main
          mv YouTube.ipa YouTube.zip
          unzip -q YouTube.zip || { echo "Failed to unzip YouTube IPA"; exit 1; }
          youtube_version=$(defaults read "$(pwd)/Payload/YouTube.app/Info" CFBundleVersion)
          echo "==> YouTube v$youtube_version downloaded!"
          sed -i '' "17s#.*#YOUTUBE_VERSION = ${youtube_version}#g" Makefile
          echo "youtube_version=${youtube_version}" >> $GITHUB_OUTPUT
        env:
          THEOS: ${{ github.workspace }}/theos
          YOUTUBE_URL: ${{ inputs.decrypted_youtube_url }}

      - name: Fix compiling & Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          sed -i '' "27s#.*#BUNDLE_ID = ${{ env.BUNDLE_ID }}#g" Makefile
          sed -i '' "26s#.*#DISPLAY_NAME = ${{ env.APP_NAME }}#g" Makefile
          sed -i '' "1s#.*#export TARGET = iphone:clang:${{ inputs.sdk_version }}:12.0#g" Makefile
          make package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/YouTube.app FINALPACKAGE=1
          echo "package=$(ls -t packages | head -n1)" >> $GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
          echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"
        env:
          THEOS: ${{ github.workspace }}/theos
          UYOU_VERSION: ${{ inputs.uyou_version }}
          BUNDLE_ID: ${{ inputs.bundle_id }}
          APP_NAME: ${{ inputs.app_name }}

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.4.3
        env:
          UYOU_VERSION: ${{ inputs.uyou_version }}
          YOUTUBE_VERSION: ${{ steps.prepare_youtube.outputs.youtube_version }}
        with:
          name: uYouEnhanced_${{ env.YOUTUBE_VERSION }}_${{ env.UYOU_VERSION }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error

      - name: Create Release
        if: ${{ inputs.create_release }}
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UYOU_VERSION: ${{ inputs.uyou_version }}
          YOUTUBE_VERSION: ${{ steps.prepare_youtube.outputs.youtube_version }}
        with:
          tag_name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          files: main/packages/*.ipa
          draft: true
